### ISSUE TITLE
Is this package abandoned?

### ISSUE THREAD

**Issue by sajaddp** [writingink/wink#365]
Dear @themsaid,
This package is very popular, do you have any plans to continue developing and handling `issues` and `PRs`?

**Comment by mrneatly** [comment]
Also interested in this topic. @themsaid do you need some help in supporting this package?

**Comment by scajal** [comment]
Bump this question.

**Comment by scajal** [comment]
Any news on this?

**Comment by thomaspalmer** [comment]
Is it worth creating a fork to continue @themsaid good work?

**Comment by tvbeek** [comment]
I did have some content with @themsaid on Twitter ( https://twitter.com/tvbeek/status/1582030207627956224 ) and I did review some PR's and send him an email but after that I didn't receive any reaction.

Before creating a fork it is important to know some things:

1. Who is interesting in maintaining the fork? (Multiple people working together is most of the time preferable)
    1. Who off them has experience maintaining an opensource project.
2. What will be the plan for this package (keep it working or adding more features)
3. Will @themsaid not adding other maintainers to this package? (Because that will be more useful for the users)

**Comment by scajal** [comment]
I'm open to help maintain a fork if someone is willing to do it.

**Comment by tvbeek** [comment]
I have send a tweet to @themsaid about it ( https://twitter.com/tvbeek/status/1630307432638365696 )

If there is no response I think it is wise to start a fork and maintain it with a group.

For anyone interested you can send me an email (see my profile for my email address  https://github.com/tvbeek ).

**Comment by themsaid** [comment]
Hey guys. Thank you for your patience.

I've been using Wink on weekly basis all this time. It works great and is used by many people without issues. It feels complete for me and I don't have ideas for anything major to add.

It is not abandoned, it's complete.

I built Wink to help people include blogs easily into their Laravel applications. I believe the mission is accomplished.

If you want to add any major changes, feel free to fork it. That's why open-source is amazing.

I'm currently working on Wink for introducing a few minor enhancements to cater for some needs I have at the moment. Nothing major. Don't expect something major :)

**Comment by scajal** [comment]
@tvbeek What about we fork the repo and start maintaining it?

**Comment by sajaddp** [comment]
Dear @themsaid
Thank you for developing this package.
Although I don't agree with you about it being perfect and many people using it without problems. In any case, every package needs care and maintenance.

Well, in my opinion, this issue does not need to be continued. 🙂

**Comment by tvbeek** [comment]
> @tvbeek What about we fork the repo and start maintaining it?

We currently see some activity and a new tag. For me it means that for now I don't see a direct reason to fork. We will see what the future will bring.
