### ISSUE TITLE
Cannot load wink

### ISSUE THREAD

**Issue by skoyah** [writingink/wink#51]
I followed all the steps on the CONTRIBUTING guide but when I try to access the wink backend, I get the following error:

```"Undefined index: /light.css (View /Users/..../resources/views/login.blade.php)"```

Did I do something wrong?

**Comment by eoghanobrien** [comment]
That's the `mix()` function call within wink failing to find the index `light.css` in the `mix-manifest.json` file at `vendor/wink`.

I have a feeling the issue is because of the following in the Wink `webpack.mix.js` file on line 35:

```js
...
    .copy('public', '../winktest/public/vendor/wink')
...
```

I reckon the path should just be './public/vendor/wink' but some recent change, probably a PR, changed this to test and never changed it back.

You should have something like the following at `public/vendor/wink/mix-manifest.json`:

```json
{
    "/app.js": "/app.js?id=35cc70ff36a96d5e3236",
    "/light.css": "/light.css?id=e05ad90466b4abd9315c",
    "/favicon.png": "/favicon.png?id=b0b34b4095fcdbb8942d"
}
```

Can you take a look and check if those files are in the correct location?

- public/vendor/wink/app.js
- public/vendor/wink/light.css
- public/vendor/wink/favicon.png

**Comment by skoyah** [comment]
The files you listed are in the correct location.

Would be nice to know if anyone else is having the same issue when doing a fresh clone.

**Comment by themsaid** [comment]
Hmmmm can you try and re-publish the assets?

**Comment by skoyah** [comment]
Did a new `php artisan wink:install` but I still get that error. I will delete de wink folder and start from scratch again. If the error persist I will let you know.

**Comment by skoyah** [comment]
I think  the problem is related with what @eoghanobrien said. In fact, when I was removing the `wink`folder from my sites directory, I found that I also had a `winktest/`directory.

This is related with that code on the webpack.mix file:
```.copy('public', '../winktest/public/vendor/wink')```

Was that intentional @themsaid, or that should be removed completely?

**Comment by skoyah** [comment]
Okay, so I think I found a way to solve this.

By default, when you are compiling the assets, It assumes that you will have a laravel project named `winktest`. 

So maybe, on the contribution guide we could describe it. Making sure that either when you create a new laravel project to package contribution, that you should run `laravel new winktest`or if the user prefers to name it something else, that they should go into the `webpack.mix.js`and  rename the `../winktest/public/vendor/wink` to `../**laravel-project-folder-name**/public/vendor/wink`.
