### ISSUE TITLE
[Road Map] Dark Theme

### ISSUE THREAD

**Issue by rbcunhadesign** [writingink/wink#83]
For the dark theme,

1. 
- Would you rather save the settings on local storage,
- A field in the wink_users table,
- Add a new table (wink_user_settings) that stores this setting and/or any new future user setting added to the application?

2.
- Create new stylesheet for dark theme and override tailwind classes,
- Check dark/light settings per component and add/remove tailwind classes accordingly?

**Comment by themsaid** [comment]
I believe that these settings should be per author, probably will be stored in a JSON field in the users table. I like JSON fields because it makes us avoid joining tables when it's not really necessary.

I think for the dark theme I think we'll utilize css variables and see if that gives us decent results. It'll require some experimenting. If that didn't work then I guess we'll use a separate tailwind config file and stylesheet.
